language: cpp
cache:
  directories:
    - $TRAVIS_BUILD_DIR/build/third_party
    - $TRAVIS_BUILD_DIR/bazel.cmake/third-party
matrix:
    include:
        - os: linux
          dist: trusty
        - os: osx
          osx_image: xcode9 
script:
    - cmake --version
    - if [ ! -d "build" ]; then mkdir build; fi
    - cd build
    - cmake -DWITH_GPU=OFF ..
    - make -j2
    - ctest
notifications:
  email:
    on_success: change
    on_failure: always
