language: cpp
os: osx
osx_image: xcode9
script:
    - mkdir build
    - cd build
    - cmake -DWITH_GPU=OFF ..
    - make -j2
    - ctest
notifications:
  email:
    on_success: change
    on_failure: always
